# Do not change any values in this file
server:
  port: ${PORT:8080}

spring:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      pool-name: Pi-Database
  main:
    allow-circular-references: true
  profiles:
    default: "local"

logging:
  level:
    "[org.springframework]": OFF
    "[org.apache]": OFF

security:
  signing-key: ${JWT_SIGNING_KEY}
  sendgrid-key: ${SENDGRID_API_KEY}
