# Workflow will build the marcs application on push to the branch and pull request for the branch.

name: Marc's Microservice Build

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Marc's Microservice Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: "14"
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Build
        env:
          APP_ENVIRONMENT: ${{ secrets.APP_ENVIRONMENT }}
          MYSQL_TEST_USERNAME: ${{ secrets.MYSQL_TEST_USERNAME }}
          MYSQL_TEST_PASSWORD: ${{ secrets.MYSQL_TEST_PASSWORD }}
          MYSQL_TEST_URL: ${{ secrets.MYSQL_TEST_URL }}
          JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY}}
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
